[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "google-auth>=2.38.0",
    "gspread>=6.2.0",
    "pydub>=0.25.1",
    "speechrecognition>=3.14.1",
    "telegram>=0.0.1",
]
